### ISSUE TITLE
States incorrect support for Trusty

### ISSUE THREAD

**Issue by xiongchiamiov** [andrewrothstein/ansible-consul#1]
The [meta information](https://github.com/andrewrothstein/ansible-consul/blob/master/meta/main.yml#L16-L18) says this role supports Ubuntu 14.04 LTS, Trusty.  However, the task [assumes systemd](https://github.com/andrewrothstein/ansible-consul/blob/master/tasks/main.yml#L45-L56), and it wasn't until [15.04](https://wiki.ubuntu.com/SystemdForUpstartUsers) that systemd replaced upstart in Ubuntu.

**Comment by andrewrothstein** [comment]
thanks for pointing that out. i should have adjusted the meta data after I tied the config to systemd. I just published a new version v1.0.2 that corrects the metadata. trusty is long in the tooth. looking forward to xenial!
